### PR TITLE
Fix for swagger template only showing blank page instead of docs.

### PR DESCRIPTION
**Pull request by laravelcoder**
This was causing my /api/docs to not work so i fixed it and now i am sharing with everyone.

### CODE REVIEW

**Comment by TemaSM** [comment]
@laravelcoder that's  incorrect way of resolving this issue.

There're special variables in config file `swaggervel.php` for that:
https://github.com/appointer/swaggervel/blob/baf079f91f545a1c809edeeb4112185358a44f50/src/config/swaggervel.php#L16
and
https://github.com/appointer/swaggervel/blob/baf079f91f545a1c809edeeb4112185358a44f50/src/config/swaggervel.php#L23
just insert `/` in front of default values.
I will publish new PR, so it will close #22 issue.

**Comment by fgreinus** [comment]
I'd really appreciate a patch for this - but yeah, this PR is (in my opinion too) not the right way to solve it, as the changes are redundant because of existing config options.

**Comment by Spartaa** [comment]
> @laravelcoder that's incorrect way of resolving this issue.
> 
> There're special variables in config file `swaggervel.php` for that:
> [swaggervel/src/config/swaggervel.php](https://github.com/appointer/swaggervel/blob/baf079f91f545a1c809edeeb4112185358a44f50/src/config/swaggervel.php#L16)
> 
> Line 16 in [baf079f](/appointer/swaggervel/commit/baf079f91f545a1c809edeeb4112185358a44f50)
> 
>      'doc-route' => 'docs', 
> 
> and
> [swaggervel/src/config/swaggervel.php](https://github.com/appointer/swaggervel/blob/baf079f91f545a1c809edeeb4112185358a44f50/src/config/swaggervel.php#L23)
> 
> Line 23 in [baf079f](/appointer/swaggervel/commit/baf079f91f545a1c809edeeb4112185358a44f50)
> 
>      'ui-resource-path' => 'vendor/swaggervel', 
> 
> @Spartaa just insert `/` in front of default values.
> I will publish new PR, so it will close #22 issue.

I am still facing the same issue
should i remove last changes? which i made by seeing "laravelcoder "

**Comment by TemaSM** [comment]
@Spartaa yes. Revert any changes made directly to sources files of `swaggervel` and apply commit (5f4313d) to your config file

**Comment by Spartaa** [comment]
@TemaSM  @fgreinus  I upload my files from local host to live server and i am recieving this error again i have checked i just move all files from here to there
is there anything you can guide me about that issue? Please

**Comment by Spartaa** [comment]
Capture

**Pull request closed without merging**
